-- ============================================================
--  CineMatch -- Modelo Relacional BASE DE DATOS LOCAL
--  Script DDL compatible con Oracle Data Modeler / Oracle DB
--  Origen: SQLite local (CapacitorSQLite) -- cinematch_local
--  Generado: 2026-04-23
-- ============================================================
--
--  Mapeo de tipos SQLite -> Oracle
--    TEXT                    -> VARCHAR2(n) / CLOB / CHAR(1)
--    INTEGER                 -> NUMBER(10)
--    REAL                    -> NUMBER
--    INTEGER AUTOINCREMENT   -> NUMBER(10) GENERATED BY DEFAULT AS IDENTITY
--
--  Convenciones:
--    - IDs de entidades propias de la app  : CHAR(36)  (UUID texto)
--    - IDs de cola_sync                    : NUMBER(10) IDENTITY
--    - Flags booleanos (S/N)               : CHAR(1)
--    - Fechas/timestamps                   : VARCHAR2(30)
--    - JSON almacenado como texto          : CLOB
--    - sync_status                         : VARCHAR2(20)
--
--  Relaciones:
--    Las FK marcadas como ON DELETE CASCADE se replican igual.
--    local_ranking_pelicula.pelicula_id -> local_pelicula.id
--    es una FK lógica (en SQLite solo era UNIQUE TEXT).
-- ============================================================


-- ------------------------------------------------------------
-- LOCAL_USUARIO
-- Caché local del perfil del usuario autenticado.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_USUARIO (
    id               CHAR(36)      CONSTRAINT PK_LOCAL_USUARIO PRIMARY KEY,
    nombre_user      VARCHAR2(255),
    nombre           VARCHAR2(255),
    apellido_1       VARCHAR2(255),
    apellido_2       VARCHAR2(255),
    email            VARCHAR2(255),
    auth_user_id     CHAR(36),
    fecha_nacimiento VARCHAR2(30),
    genero           VARCHAR2(50),
    avatar_url       VARCHAR2(4000),
    bio              CLOB,
    radio_conex      NUMBER(10),
    busqueda_abierta CHAR(1)       CONSTRAINT CHK_USR_BUSQUEDA CHECK (busqueda_abierta IN ('S','N')),
    sync_status      VARCHAR2(20)  DEFAULT 'synced' NOT NULL,
    synced_at        VARCHAR2(30)  NOT NULL
);


-- ------------------------------------------------------------
-- LOCAL_PELICULA
-- Caché local de películas sincronizadas desde TMDB / Supabase.
-- generos_json almacena el array de géneros serializado en JSON.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_PELICULA (
    id              CHAR(36)      CONSTRAINT PK_LOCAL_PELICULA PRIMARY KEY,
    tmdb_id         NUMBER(10),
    titulo          VARCHAR2(500) NOT NULL,
    sinopsis        CLOB,
    poster_url      VARCHAR2(4000),
    fecha_estreno   VARCHAR2(30),
    duracion_min    NUMBER(10),
    promedio_votos  NUMBER,
    idioma_original VARCHAR2(10),
    generos_json    CLOB,
    synced_at       VARCHAR2(30)  NOT NULL,
    CONSTRAINT UQ_LOCAL_PELICULA_TMDB UNIQUE (tmdb_id)
);


-- ------------------------------------------------------------
-- LOCAL_CONVERSACION
-- Caché local de conversaciones de chat.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_CONVERSACION (
    id          CHAR(36)     CONSTRAINT PK_LOCAL_CONVERSACION PRIMARY KEY,
    sync_status VARCHAR2(20) DEFAULT 'synced' NOT NULL,
    synced_at   VARCHAR2(30) NOT NULL
);


-- ------------------------------------------------------------
-- LOCAL_LISTA
-- Listas de películas creadas por el usuario (offline-first).
-- peliculas_ids almacena un array JSON de tmdb_ids.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_LISTA (
    local_id      CHAR(36)     CONSTRAINT PK_LOCAL_LISTA PRIMARY KEY,
    server_id     CHAR(36),
    usuario_id    CHAR(36)     NOT NULL,
    nombre        VARCHAR2(500) NOT NULL,
    descripcion   CLOB,
    peliculas_ids CLOB         DEFAULT '[]' NOT NULL,
    estado        VARCHAR2(20) DEFAULT 'activa' NOT NULL,
    sync_status   VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    synced_at     VARCHAR2(30),
    created_at    VARCHAR2(30) NOT NULL,
    CONSTRAINT CHK_LISTA_ESTADO   CHECK (estado IN ('activa','borrada')),
    CONSTRAINT FK_LISTA_USUARIO   FOREIGN KEY (usuario_id) REFERENCES LOCAL_USUARIO(id) ON DELETE CASCADE
);


-- ------------------------------------------------------------
-- LOCAL_RESENA
-- Reseñas creadas localmente, pendientes o sincronizadas.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_RESENA (
    local_id      CHAR(36)     CONSTRAINT PK_LOCAL_RESENA PRIMARY KEY,
    server_id     CHAR(36),
    usuario_id    CHAR(36)     NOT NULL,
    pelicula_id   CHAR(36)     NOT NULL,
    calificacion  NUMBER(10)   NOT NULL,
    comentario    CLOB,
    tiene_spoiler CHAR(1)      DEFAULT 'N' NOT NULL,
    sync_status   VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    synced_at     VARCHAR2(30),
    created_at    VARCHAR2(30) NOT NULL,
    CONSTRAINT CHK_RESENA_CALIFICACION CHECK (calificacion BETWEEN 1 AND 10),
    CONSTRAINT CHK_RESENA_SPOILER      CHECK (tiene_spoiler IN ('S','N')),
    CONSTRAINT FK_RESENA_USUARIO       FOREIGN KEY (usuario_id)  REFERENCES LOCAL_USUARIO(id)  ON DELETE CASCADE,
    CONSTRAINT FK_RESENA_PELICULA      FOREIGN KEY (pelicula_id) REFERENCES LOCAL_PELICULA(id) ON DELETE CASCADE
);


-- ------------------------------------------------------------
-- LOCAL_MENSAJE
-- Mensajes de chat almacenados localmente.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_MENSAJE (
    local_id        CHAR(36)     CONSTRAINT PK_LOCAL_MENSAJE PRIMARY KEY,
    server_id       CHAR(36),
    emisor_id       CHAR(36)     NOT NULL,
    conversacion_id CHAR(36)     NOT NULL,
    contenido       CLOB         NOT NULL,
    leido           CHAR(1)      DEFAULT 'N' NOT NULL,
    sync_status     VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    created_at      VARCHAR2(30) NOT NULL,
    CONSTRAINT CHK_MENSAJE_LEIDO     CHECK (leido IN ('S','N')),
    CONSTRAINT FK_MENSAJE_EMISOR     FOREIGN KEY (emisor_id)       REFERENCES LOCAL_USUARIO(id)       ON DELETE CASCADE,
    CONSTRAINT FK_MENSAJE_CONV       FOREIGN KEY (conversacion_id) REFERENCES LOCAL_CONVERSACION(id)  ON DELETE CASCADE
);


-- ------------------------------------------------------------
-- LOCAL_USUARIO_GENERO_PREFERENCIA
-- Peso de afinidad del usuario por género (media ponderada Welford).
-- Un registro por par (usuario_id, tmdb_genero_id).
-- ------------------------------------------------------------
CREATE TABLE LOCAL_USUARIO_GENERO_PREFERENCIA (
    id             CHAR(36)     CONSTRAINT PK_LOCAL_UGP PRIMARY KEY,
    usuario_id     CHAR(36)     NOT NULL,
    tmdb_genero_id NUMBER(10)   NOT NULL,
    nombre_genero  VARCHAR2(255) NOT NULL,
    peso_pref      NUMBER       DEFAULT 0 NOT NULL,
    conteo         NUMBER(10)   DEFAULT 0 NOT NULL,
    sync_status    VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    synced_at      VARCHAR2(30),
    created_at     VARCHAR2(30) NOT NULL,
    CONSTRAINT UQ_UGP_USUARIO_GENERO UNIQUE (usuario_id, tmdb_genero_id),
    CONSTRAINT FK_UGP_USUARIO        FOREIGN KEY (usuario_id) REFERENCES LOCAL_USUARIO(id) ON DELETE CASCADE
);


-- ------------------------------------------------------------
-- LOCAL_PELICULA_VISTA
-- Registro de películas marcadas como vistas (offline-first).
-- UNIQUE(usuario_id, tmdb_id) evita duplicados por película.
-- ------------------------------------------------------------
CREATE TABLE LOCAL_PELICULA_VISTA (
    local_id         CHAR(36)     CONSTRAINT PK_LOCAL_PELICULA_VISTA PRIMARY KEY,
    server_id        CHAR(36),
    usuario_id       CHAR(36)     NOT NULL,
    pelicula_id      CHAR(36)     NOT NULL,
    tmdb_id          NUMBER(10)   NOT NULL,
    titulo           VARCHAR2(500) NOT NULL,
    poster_url       VARCHAR2(4000),
    genero_principal VARCHAR2(255),
    fecha_vista      VARCHAR2(30) NOT NULL,
    sync_status      VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    synced_at        VARCHAR2(30),
    CONSTRAINT UQ_VISTA_USUARIO_TMDB  UNIQUE (usuario_id, tmdb_id),
    CONSTRAINT FK_VISTA_USUARIO       FOREIGN KEY (usuario_id)  REFERENCES LOCAL_USUARIO(id)  ON DELETE CASCADE,
    CONSTRAINT FK_VISTA_PELICULA      FOREIGN KEY (pelicula_id) REFERENCES LOCAL_PELICULA(id) ON DELETE CASCADE
);


-- ------------------------------------------------------------
-- LOCAL_RANKING_PELICULA
-- Caché del ranking mundial descargado desde Supabase.
-- pelicula_id referencia LOCAL_PELICULA (UNIQUE, 1 fila por película).
-- ------------------------------------------------------------
CREATE TABLE LOCAL_RANKING_PELICULA (
    id                    CHAR(36)      CONSTRAINT PK_LOCAL_RANKING PRIMARY KEY,
    pelicula_id           CHAR(36)      NOT NULL,
    tmdb_id               NUMBER(10)    NOT NULL,
    titulo                VARCHAR2(500) NOT NULL,
    poster_url            VARCHAR2(4000),
    posicion              NUMBER(10)    NOT NULL,
    promedio_calificacion NUMBER,
    total_resenas         NUMBER(10)    DEFAULT 0 NOT NULL,
    synced_at             VARCHAR2(30),
    CONSTRAINT UQ_RANKING_PELICULA_ID UNIQUE (pelicula_id),
    CONSTRAINT FK_RANKING_PELICULA    FOREIGN KEY (pelicula_id) REFERENCES LOCAL_PELICULA(id)
);


-- ------------------------------------------------------------
-- COLA_SYNC
-- Cola de operaciones pendientes de sincronización con Supabase.
-- Registra INSERT/UPDATE/DELETE offline para reproducir en línea.
-- ------------------------------------------------------------
CREATE TABLE COLA_SYNC (
    id           NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY
                               CONSTRAINT PK_COLA_SYNC PRIMARY KEY,
    tabla        VARCHAR2(100) NOT NULL,
    registro_id  VARCHAR2(36)  NOT NULL,
    operacion    VARCHAR2(10)  NOT NULL,
    intentos     NUMBER(10)    DEFAULT 0 NOT NULL,
    status       VARCHAR2(20)  DEFAULT 'pendiente' NOT NULL,
    created_at   VARCHAR2(30)  NOT NULL,
    last_attempt VARCHAR2(30),
    CONSTRAINT CHK_COLA_OPERACION CHECK (operacion IN ('INSERT','UPDATE','DELETE'))
);


-- ------------------------------------------------------------
-- ÍNDICES
-- ------------------------------------------------------------
CREATE INDEX IDX_VISTA_USUARIO      ON LOCAL_PELICULA_VISTA(usuario_id);
CREATE INDEX IDX_VISTA_TMDB         ON LOCAL_PELICULA_VISTA(tmdb_id);
CREATE INDEX IDX_LISTA_USUARIO      ON LOCAL_LISTA(usuario_id);
CREATE INDEX IDX_RESENA_USUARIO     ON LOCAL_RESENA(usuario_id);
CREATE INDEX IDX_RESENA_PELICULA    ON LOCAL_RESENA(pelicula_id);
CREATE INDEX IDX_MENSAJE_CONV       ON LOCAL_MENSAJE(conversacion_id);
CREATE INDEX IDX_COLA_STATUS        ON COLA_SYNC(status);
CREATE INDEX IDX_COLA_TABLA         ON COLA_SYNC(tabla);
CREATE INDEX IDX_PREF_GENERO_USR    ON LOCAL_USUARIO_GENERO_PREFERENCIA(usuario_id);
CREATE INDEX IDX_PREF_GENERO_TMDB   ON LOCAL_USUARIO_GENERO_PREFERENCIA(tmdb_genero_id);


-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
