-- ============================================================
--  CineMatch -- Modelo Relacional
--  Script DDL compatible con Oracle Data Modeler / Oracle DB
--  Origen: Supabase (PostgreSQL) proyecto vfhnqujmbaemmmhfurwp
--  Generado: 2026-04-23
-- ============================================================
--
--  Mapeo de tipos PostgreSQL -> Oracle
--    uuid                    -> CHAR(36)
--    integer                 -> NUMBER(10)
--    character varying/text  -> VARCHAR2(n) / CLOB
--    numeric                 -> NUMBER
--    date                    -> DATE
--    timestamp with time zone-> TIMESTAMP WITH TIME ZONE
--    character (bpchar)      -> CHAR(1)
--
--  Nota: la tabla auth.users pertenece al esquema interno de
--  Supabase y no se replica aqui; la FK de USUARIO.auth_user_id
--  se documenta como comentario.
-- ============================================================


-- ------------------------------------------------------------
-- GENERO
-- ------------------------------------------------------------
CREATE TABLE GENERO (
    id         NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY
                             CONSTRAINT PK_GENERO PRIMARY KEY,
    nombre     VARCHAR2(255) NOT NULL,
    slug       VARCHAR2(255) NOT NULL,
    tmdb_id    NUMBER(10),
    CONSTRAINT UQ_GENERO_NOMBRE UNIQUE (nombre),
    CONSTRAINT UQ_GENERO_SLUG   UNIQUE (slug)
);


-- ------------------------------------------------------------
-- USUARIO
-- (auth_user_id referencia auth.users de Supabase)
-- ------------------------------------------------------------
CREATE TABLE USUARIO (
    id                  CHAR(36)      DEFAULT SYS_GUID()
                                      CONSTRAINT PK_USUARIO PRIMARY KEY,
    auth_user_id        CHAR(36)      NOT NULL,
    nombre_user         VARCHAR2(255) NOT NULL,
    nombre              VARCHAR2(255) NOT NULL,
    apellido_1          VARCHAR2(255) NOT NULL,
    apellido_2          VARCHAR2(255),
    email               VARCHAR2(255) NOT NULL,
    fecha_nacimiento    DATE          NOT NULL,
    genero              VARCHAR2(50)  NOT NULL,
    radio_conex         NUMBER(10)    NOT NULL,
    busqueda_abierta    CHAR(1)       NOT NULL,
    avatar_url          VARCHAR2(4000),
    bio                 CLOB,
    latitud             NUMBER,
    longitud            NUMBER,
    fecha_creacion_user TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_USUARIO_AUTH_USER_ID UNIQUE (auth_user_id),
    CONSTRAINT UQ_USUARIO_NOMBRE_USER  UNIQUE (nombre_user),
    CONSTRAINT UQ_USUARIO_EMAIL        UNIQUE (email)
);


-- ------------------------------------------------------------
-- PELICULA
-- ------------------------------------------------------------
CREATE TABLE PELICULA (
    id               CHAR(36)      DEFAULT SYS_GUID()
                                   CONSTRAINT PK_PELICULA PRIMARY KEY,
    tmdb_id          NUMBER(10)    NOT NULL,
    titulo           VARCHAR2(500) NOT NULL,
    sinopsis         CLOB,
    fecha_estreno    DATE,
    poster_url       VARCHAR2(4000),
    duracion_min     NUMBER(10),
    promedio_votos   NUMBER,
    idioma_original  VARCHAR2(10),
    fecha_creacion   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_PELICULA_TMDB_ID UNIQUE (tmdb_id)
);


-- ------------------------------------------------------------
-- PELICULA_GENERO  (tabla de union N:M)
-- ------------------------------------------------------------
CREATE TABLE PELICULA_GENERO (
    pelicula_id  CHAR(36)   NOT NULL,
    genero_id    NUMBER(10) NOT NULL,
    CONSTRAINT PK_PELICULA_GENERO    PRIMARY KEY (pelicula_id, genero_id),
    CONSTRAINT FK_PEL_GEN_PELICULA   FOREIGN KEY (pelicula_id) REFERENCES PELICULA(id),
    CONSTRAINT FK_PEL_GEN_GENERO     FOREIGN KEY (genero_id)   REFERENCES GENERO(id)
);


-- ------------------------------------------------------------
-- CONEXION
-- ------------------------------------------------------------
CREATE TABLE CONEXION (
    id               CHAR(36)      DEFAULT SYS_GUID()
                                   CONSTRAINT PK_CONEXION PRIMARY KEY,
    solicitante_id   CHAR(36)      NOT NULL,
    destinatario_id  CHAR(36)      NOT NULL,
    estado           VARCHAR2(50)  NOT NULL,
    compatibilidad   NUMBER,
    fecha_creacion   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_CONEX_SOLICITANTE  FOREIGN KEY (solicitante_id)  REFERENCES USUARIO(id),
    CONSTRAINT FK_CONEX_DESTINATARIO FOREIGN KEY (destinatario_id) REFERENCES USUARIO(id)
);


-- ------------------------------------------------------------
-- CONVERSACION
-- ------------------------------------------------------------
CREATE TABLE CONVERSACION (
    id             CHAR(36) DEFAULT SYS_GUID()
                            CONSTRAINT PK_CONVERSACION PRIMARY KEY,
    conexion_id    CHAR(36) NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_CONV_CONEXION  UNIQUE (conexion_id),
    CONSTRAINT FK_CONV_CONEXION  FOREIGN KEY (conexion_id) REFERENCES CONEXION(id)
);


-- ------------------------------------------------------------
-- MENSAJE
-- ------------------------------------------------------------
CREATE TABLE MENSAJE (
    id               CHAR(36) DEFAULT SYS_GUID()
                              CONSTRAINT PK_MENSAJE PRIMARY KEY,
    conversacion_id  CHAR(36) NOT NULL,
    emisor_id        CHAR(36) NOT NULL,
    contenido        CLOB     NOT NULL,
    leido            CHAR(1)  NOT NULL,
    fecha_envio      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_CONVERSACION FOREIGN KEY (conversacion_id) REFERENCES CONVERSACION(id),
    CONSTRAINT FK_MSG_EMISOR       FOREIGN KEY (emisor_id)       REFERENCES USUARIO(id)
);


-- ------------------------------------------------------------
-- NOTIFICACION
-- ------------------------------------------------------------
CREATE TABLE NOTIFICACION (
    id             CHAR(36)      DEFAULT SYS_GUID()
                                 CONSTRAINT PK_NOTIFICACION PRIMARY KEY,
    usuario_id     CHAR(36)      NOT NULL,
    tipo           VARCHAR2(100) NOT NULL,
    titulo         VARCHAR2(255) NOT NULL,
    mensaje        CLOB,
    leida          CHAR(1)       NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    remitente_id   CHAR(36),
    referencia_id  CHAR(36),
    CONSTRAINT FK_NOTIF_USUARIO    FOREIGN KEY (usuario_id)    REFERENCES USUARIO(id),
    CONSTRAINT FK_NOTIF_REMITENTE  FOREIGN KEY (remitente_id)  REFERENCES USUARIO(id),
    CONSTRAINT FK_NOTIF_REFERENCIA FOREIGN KEY (referencia_id) REFERENCES CONEXION(id)
);


-- ------------------------------------------------------------
-- LISTA_PELICULAS
-- (pelicula_id era un array en Postgres; se modela como lista
--  de tmdb_ids separados por coma o se puede normalizar aparte)
-- ------------------------------------------------------------
CREATE TABLE LISTA_PELICULAS (
    id             CHAR(36)      DEFAULT SYS_GUID()
                                 CONSTRAINT PK_LISTA_PELICULAS PRIMARY KEY,
    usuario_id     CHAR(36)      NOT NULL,
    nombre         VARCHAR2(500) DEFAULT 'Mi lista' NOT NULL,
    descripcion    CLOB,
    estado         VARCHAR2(20)  NOT NULL,
    pelicula_ids   CLOB,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_LISTA_USUARIO   FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
    CONSTRAINT CHK_LISTA_ESTADO   CHECK (estado IN ('activa', 'borrada'))
);


-- ------------------------------------------------------------
-- RECOMENDACION
-- ------------------------------------------------------------
CREATE TABLE RECOMENDACION (
    id             CHAR(36)      DEFAULT SYS_GUID()
                                 CONSTRAINT PK_RECOMENDACION PRIMARY KEY,
    usuario_id     CHAR(36)      NOT NULL,
    pelicula_id    CHAR(36)      NOT NULL,
    puntaje        NUMBER        NOT NULL,
    razon          VARCHAR2(500),
    vista          CHAR(1)       NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_RECOM_USUARIO  FOREIGN KEY (usuario_id)  REFERENCES USUARIO(id),
    CONSTRAINT FK_RECOM_PELICULA FOREIGN KEY (pelicula_id) REFERENCES PELICULA(id)
);


-- ------------------------------------------------------------
-- RESENA
-- ------------------------------------------------------------
CREATE TABLE RESENA (
    id             CHAR(36) DEFAULT SYS_GUID()
                            CONSTRAINT PK_RESENA PRIMARY KEY,
    usuario_id     CHAR(36) NOT NULL,
    pelicula_id    CHAR(36) NOT NULL,
    calificacion   NUMBER(10) NOT NULL,
    comentario     CLOB,
    tiene_spoiler  CHAR(1)  NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_RESENA_USUARIO  FOREIGN KEY (usuario_id)  REFERENCES USUARIO(id),
    CONSTRAINT FK_RESENA_PELICULA FOREIGN KEY (pelicula_id) REFERENCES PELICULA(id)
);


-- ------------------------------------------------------------
-- USUARIO_GENERO_PREFERENCIA
-- ------------------------------------------------------------
CREATE TABLE USUARIO_GENERO_PREFERENCIA (
    id                  CHAR(36)   DEFAULT SYS_GUID()
                                   CONSTRAINT PK_UGP PRIMARY KEY,
    usuario_id          CHAR(36)   NOT NULL,
    genero_id           NUMBER(10) NOT NULL,
    peso_pref           NUMBER     NOT NULL,
    fecha_creacion_pref TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_UGP_USUARIO FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
    CONSTRAINT FK_UGP_GENERO  FOREIGN KEY (genero_id)  REFERENCES GENERO(id)
);


-- ------------------------------------------------------------
-- PELICULA_VISTA
-- ------------------------------------------------------------
CREATE TABLE PELICULA_VISTA (
    id           CHAR(36) DEFAULT SYS_GUID()
                          CONSTRAINT PK_PELICULA_VISTA PRIMARY KEY,
    usuario_id   CHAR(36) NOT NULL,
    pelicula_id  CHAR(36) NOT NULL,
    fecha_vista  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PV_USUARIO  FOREIGN KEY (usuario_id)  REFERENCES USUARIO(id),
    CONSTRAINT FK_PV_PELICULA FOREIGN KEY (pelicula_id) REFERENCES PELICULA(id)
);


-- ------------------------------------------------------------
-- RANKING_PELICULA
-- (tabla de cache/materializada con FK a PELICULA)
-- ------------------------------------------------------------
CREATE TABLE RANKING_PELICULA (
    id                    CHAR(36)      DEFAULT SYS_GUID()
                                        CONSTRAINT PK_RANKING_PELICULA PRIMARY KEY,
    pelicula_id           CHAR(36)      NOT NULL,
    tmdb_id               NUMBER(10)    NOT NULL,
    titulo                VARCHAR2(500) NOT NULL,
    poster_url            VARCHAR2(4000),
    posicion              NUMBER(10)    DEFAULT 0 NOT NULL,
    promedio_calificacion NUMBER        DEFAULT 0 NOT NULL,
    total_resenas         NUMBER(10)    DEFAULT 0 NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_RANKING_PELICULA_ID  UNIQUE (pelicula_id),
    CONSTRAINT FK_RANKING_PELICULA     FOREIGN KEY (pelicula_id) REFERENCES PELICULA(id)
);


-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
